spring:
  config:
    activate.on-profile: test

  application.name: ShareItAppTest
  main.banner-mode: OFF

  datasource:
    username: shareit
    password: shareit
    url: jdbc:h2:mem:shareit
    driver-class-name: org.h2.Driver